services:
  emailservice.api:
    build:
      context: .
      dockerfile: src/EmailService.Api/Dockerfile

  emailservice.webapp:
    build:
      context: .
      dockerfile: src/EmailService.WebApp/Dockerfile
    depends_on:
      - emailservice.api