services:
  emailservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EMAIL__SENDER=${EMAIL__SENDER}
      - EMAIL__PASSWORD=${EMAIL__PASSWORD}
      - CONNECTIONSTRINGS__PASSWORD=${CONNECTIONSTRINGS__PASSWORD}
      - CONNECTIONSTRINGS__USER=${CONNECTIONSTRINGS__USER}
    ports:
      - "5000:80"
    depends_on:
      db:
        condition: service_healthy

  emailservice.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${CONNECTIONSTRINGS__USER}
      POSTGRES_PASSWORD: ${CONNECTIONSTRINGS__PASSWORD}
      POSTGRES_DB: EmailServiceDb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
